# Generated by Django 6.0.2 on 2026-02-25 00:00

from django.conf import settings
from django.db import migrations


def assign_owner_to_superuser(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    superuser = User.objects.filter(is_superuser=True).order_by("id").first()
    if superuser is None:
        raise RuntimeError("Create a superuser before applying this migration.")

    Category = apps.get_model("transactions", "Category")
    Transaction = apps.get_model("transactions", "Transaction")

    Category.objects.filter(owner__isnull=True).update(owner=superuser)
    Transaction.objects.filter(owner__isnull=True).update(owner=superuser)


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_add_owner_fields"),
    ]

    operations = [
        migrations.RunPython(assign_owner_to_superuser, migrations.RunPython.noop),
    ]
